name: juror-er-infra
trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "hmcts"

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: action
    displayName: Action
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: location
    displayName: Location
    type: string
    default: "UK South"
    values:
      - "UK South"

  - name: overrideAction
    displayName: Override Action
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

variables:
  - name: timeoutInMinutes
    value: 60
  - name: project
    value: "juror-er-infra"
  - name: product
    value: "sds-platform"
  - name: terraformInitSubscription
    value: "74dacd4f-a248-45bb-a2f0-af700dc4cf68"
  - name: action
    value: ${{ parameters.action }}
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries
  - name: environment
    value: stg

stages:
  - stage: Init
    jobs:
      - job: TerraformInit
        displayName: "Initialize Terraform"
        steps:
          - checkout: self
          - script: terraform init
            displayName: "Terraform Init"
            workingDirectory: $(System.DefaultWorkingDirectory)

  - stage: Plan
    dependsOn: Init
    jobs:
      - job: Plan
        displayName: "Plan Terraform Changes"
        steps:
          - checkout: self
          - script: terraform plan -out=tfplan
            displayName: "Terraform Plan"
            workingDirectory: $(System.DefaultWorkingDirectory)

  - stage: Apply
    dependsOn: Plan
    condition: eq('${{ parameters.action }}', 'apply')
    jobs:
      - job: TerraformApply
        displayName: "Apply Terraform Changes"
        steps:
          - checkout: self
          - script: terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            workingDirectory: $(System.DefaultWorkingDirectory)
