name: juror-er-infra
trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "hmcts"

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: action
    displayName: Action
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: location
    displayName: Location
    type: string
    default: "UK South"
    values:
      - "UK South"

  - name: overrideAction
    displayName: Override Action
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

variables:
  - name: timeoutInMinutes
    value: 60
  - name: project
    value: "juror-er-infra"
  - name: product
    value: "sds-platform"
  - name: terraformInitSubscription
    value: "74dacd4f-a248-45bb-a2f0-af700dc4cf68"
  - name: action
    value: ${{ parameters.action }}
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries
  - name: environment
    value: stg
  - name: disable_terraform_nagger
    value: true

stages:
  - stage: Precheck
    displayName: 'Pre-deployment Check'
    condition: and(succeeded(), ne(variables['disable_terraform_nagger'], true))
    jobs:
      - job:
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'DCD-CFT-Sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - stage: deploy
    displayName: 'Deploy Infrastructure'
    condition: succeeded()
    jobs:
      - job: PlanAndApply
        steps:
          - template: steps/terraform.yaml@cnp-azuredevops-libraries
            parameters:
              location: ${{ parameters.location }}
              serviceConnection: "DTS-SHAREDSERVICES-SBOX"
              product: ${{ variables.product }}
              overrideAction: ${{ parameters.overrideAction }}
              environment: "sbox"
              component: "lab"
              terraformInitSubscription: ${{ variables.terraformInitSubscription }}
              tfVarsFile: NULL
              disableTerraformNagger: true
              initCommandOptions: >
                -reconfigure
              planCommandOptions: >
                -compact-warnings
                -lock-timeout=30s