name: juror-er-infra
trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "hmcts"

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: action
    displayName: Action
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: location
    displayName: Location
    type: string
    default: "UK South"
    values:
      - "UK South"

  - name: overrideAction
    displayName: Override Action
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

variables:
  timeoutInMinutes: 60

stages:
  - stage: Init
    jobs:
      - job: TerraformInit
        displayName: "Initialize Terraform"
        steps:
          - script: terraform init
            displayName: "Terraform Init"
            workingDirectory: $(System.DefaultWorkingDirectory)/juror-er-infra

  - stage: Plan
    dependsOn: Init
    jobs:
      - job: Plan
        steps:
          - script: terraform plan -out=tfplan
            displayName: "Terraform Plan"
            workingDirectory: $(System.DefaultWorkingDirectory)/juror-er-infra
          - script: |
              if [ "${{ parameters.action }}" == "apply" ]; then
                terraform apply -auto-approve tfplan
              fi
            displayName: "Terraform Apply"
            workingDirectory: $(System.DefaultWorkingDirectory)/juror-er-infra