parameters:
- name: subscriptionEndpoint
  type: string
- name: synapseName
  type: string
- name: resourceGroup
  type: string
  default: mi-$(environment)-rg
- name: env
  type: string
  default: $(environment)
- name: agentPool
  type: string
  default: hmcts-ss-$(environment)
- name: triggers
  type: string
  default: '*'
- name: dependsOn
  type: string
  default: ''
- name: enableTriggers
  default: false
- name: validateOnly
  type: boolean
  default: true
jobs:
- deployment: deploy_synapse
  displayName: 'Deploy Synapse Workspace'
  pool:
    vmImage: ubuntu-latest
  dependsOn: ${{ parameters.dependsOn }}
  condition: succeeded()
  variables:
    packageWheelName: 'none'
    ${{ if eq(parameters.env, 'stg') }}:
      postgresServer: 'juror-api-demoa.postgres.database.azure.com'
    ${{ else }}:
      postgresServer: 'juror-api-${{ parameters.env }}.postgres.database.azure.com'
    ${{ if or(ne(parameters.validateOnly, true),and(eq(variables['isMain'], true), eq(variables['isAutoTriggered'], true)))}}:
      operation: 'validateDeploy'
    ${{ else }}:
      operation: 'validate'
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          clean: true
        - bash: |
              echo "operation=${{ variables.operation }}"
              echo "PG server ${{ variables.postgresServer }}"
              echo "Enviroment ${{ parameters.env }}"
          displayName: 'Print operation'
        - task: AzureCLI@2
          displayName: Get Subscription ID
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              SUB_ID=$(az account show --query id -o tsv)
              echo "##vso[task.setvariable variable=SUBSCRIPTION_ID]$SUB_ID"


        - task: toggle-triggers-dev@2
          displayName: 'Disable triggers'
          condition: ne(${{ parameters.validateOnly }}, true)
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ResourceGroupName: ${{ parameters.resourceGroup }}
            WorkspaceName: ${{ parameters.synapseName }}
            ToggleOn: false
            Triggers: '*'
        - task: Synapse workspace deployment@2
          displayName: 'Synapse deployment task for workspace: ${{ parameters.synapseName }}'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ResourceGroupName: ${{ parameters.resourceGroup }}
            operation: ${{ variables.operation }}
            ArtifactsFolder: 'synapse'
            TargetWorkspaceName: ${{ parameters.synapseName }}
            DeleteArtifactsNotInTemplate: false
            DeployManagedPrivateEndpoints: false
            FailOnMissingOverrides: false
            Environment: 'prod'
            npmpackage: 'prod'
            OverrideArmParameters:  >
              -workspaceName ${{ parameters.synapseName }} 
              -AzurePostgreSqlEricSchema_properties_typeProperties_server "${{ variables.postgresServer }}"
              -LS_bais_bau_etf_properties_typeProperties_serviceEndpoint "https://baubais${{ parameters.env }}.file.core.windows.net/"
              -LS_Juror_Portal_properties_typeProperties_serviceEndpoint "https://jurorsa${{ parameters.env }}.blob.core.windows.net"
              -LS_juror_eric_kv_properties_typeProperties_baseUrl "https://baubais-${{ parameters.env }}-kv.vault.azure.net/"
              -TR_new_file_properties_typeProperties_scope "/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/baubais-data-factory-rg-${{ parameters.env }}/providers/Microsoft.Storage/storageAccounts/baubaisadfsa${{ parameters.env }}"
              --verbose 
              
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.Repository.LocalPath)/ExportedArtifacts'
            artifact: 'ArmTemplates'
            publishLocation: 'pipeline'

        - task: toggle-triggers-dev@2
          displayName: 'Restart triggers'
          condition: and(eq(${{ parameters.enableTriggers }}, true), ne(${{ parameters.validateOnly }}, true))
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ResourceGroupName: ${{ parameters.resourceGroup }}
            WorkspaceName: ${{ parameters.synapseName }}
            ToggleOn: true
            Triggers: ${{ parameters.triggers }}
